name: WinGet submission on release

on:
  workflow_dispatch:
  release:
    types: [released]

jobs:
  winget:
    name: Publish to WinGet
    runs-on: windows-latest

    steps:
      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: Radekyspec.StartLive
          version: ${{ github.event.release.tag_name }}
          installers-regex: '^StartLive-Setup\.exe$'
          token: ${{ secrets.PT_WINGET }}
